"""initial tables

Revision ID: b2c94e8565bf
Revises: 
Create Date: 2026-04-12 09:48:59.015020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c94e8565bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='公司名称'),
    sa.Column('sector', sa.String(length=100), nullable=False, comment='所属板块'),
    sa.Column('therapeutic_area', sa.String(length=200), nullable=False, comment='治疗领域（如: Oncology, Immunology）'),
    sa.Column('priority', sa.String(length=10), nullable=False, comment='优先级: high / medium'),
    sa.Column('track_fda', sa.Boolean(), nullable=False, comment='是否跟踪 FDA 审批'),
    sa.Column('track_trials', sa.Boolean(), nullable=False, comment='是否跟踪临床试验'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('notes', sa.Text(), nullable=False, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('catalysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型: pdufa / pcd / earnings / adcom / other'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='事件标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='事件描述'),
    sa.Column('event_date', sa.Date(), nullable=False, comment='事件日期'),
    sa.Column('importance', sa.String(length=20), nullable=False, comment='重要性: high / medium / low'),
    sa.Column('reminded_90d', sa.Boolean(), nullable=False),
    sa.Column('reminded_30d', sa.Boolean(), nullable=False),
    sa.Column('reminded_7d', sa.Boolean(), nullable=False),
    sa.Column('reminded_3d', sa.Boolean(), nullable=False),
    sa.Column('reminded_1d', sa.Boolean(), nullable=False),
    sa.Column('reminded_0d', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalysts_company_id'), 'catalysts', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalysts_event_date'), 'catalysts', ['event_date'], unique=False)
    op.create_table('clinical_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('nct_id', sa.String(length=20), nullable=False, comment='ClinicalTrials.gov 注册号'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='试验标题'),
    sa.Column('phase', sa.String(length=20), nullable=False, comment='试验阶段: Phase 1 / Phase 2 / Phase 3 / Phase 4'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='试验状态: Recruiting / Active, not recruiting / Completed / Terminated / etc.'),
    sa.Column('conditions', sa.Text(), nullable=True, comment='适应症（逗号分隔）'),
    sa.Column('interventions', sa.Text(), nullable=True, comment='干预措施（药物名称等）'),
    sa.Column('primary_completion_date', sa.Date(), nullable=True, comment='主要完成日期 (PCD)'),
    sa.Column('study_completion_date', sa.Date(), nullable=True, comment='研究完成日期'),
    sa.Column('enrollment', sa.Integer(), nullable=True, comment='入组人数'),
    sa.Column('previous_status', sa.String(length=50), nullable=True, comment='上次记录时的状态（用于变更检测）'),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True, comment='ClinicalTrials.gov 上的更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_trials_company_id'), 'clinical_trials', ['company_id'], unique=False)
    op.create_index(op.f('ix_clinical_trials_nct_id'), 'clinical_trials', ['nct_id'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='新闻标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='新闻正文'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='数据来源: finnhub / fda / sec / clinical_trials'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='原文链接'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='事件类型: fda_approval / clinical_trial / earnings / partnership / safety_alert'),
    sa.Column('fingerprint', sa.String(length=64), nullable=False, comment='新闻指纹 (SHA-256)，用于去重'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='新闻发布时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_company_id'), 'news', ['company_id'], unique=False)
    op.create_index(op.f('ix_news_fingerprint'), 'news', ['fingerprint'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False, comment='分析级别: 1=GPT-4o-mini 初筛, 2=Claude Sonnet 深度分析'),
    sa.Column('sentiment', sa.String(length=20), nullable=False, comment='情感判断: bullish / bearish / neutral'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='置信度 0.0-1.0'),
    sa.Column('impact_level', sa.String(length=20), nullable=False, comment='影响级别: high / medium / low'),
    sa.Column('impact_duration', sa.String(length=20), nullable=True, comment='影响时长: short_term / medium_term / long_term'),
    sa.Column('summary_cn', sa.Text(), nullable=False, comment='中文摘要'),
    sa.Column('detailed_analysis', sa.JSON(), nullable=True, comment='深度分析详情 (Level 2): direct_impact, pipeline_impact, etc.'),
    sa.Column('related_tickers', sa.JSON(), nullable=True, comment='关联股票代码列表'),
    sa.Column('key_dates', sa.JSON(), nullable=True, comment='后续需要关注的关键日期'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_news_id'), 'analyses', ['news_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_news_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_news_fingerprint'), table_name='news')
    op.drop_index(op.f('ix_news_company_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_clinical_trials_nct_id'), table_name='clinical_trials')
    op.drop_index(op.f('ix_clinical_trials_company_id'), table_name='clinical_trials')
    op.drop_table('clinical_trials')
    op.drop_index(op.f('ix_catalysts_event_date'), table_name='catalysts')
    op.drop_index(op.f('ix_catalysts_company_id'), table_name='catalysts')
    op.drop_table('catalysts')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
